[package]
name = "cargo-near"
version = "0.3.1"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2021"
rust-version = "1.60.0"
description = "Cargo extension for building Rust smart contracts on NEAR"
readme = "README.md"
repository = "https://github.com/near/cargo-near"
license = "MIT OR Apache-2.0"
keywords = ["cargo", "near", "contract", "abi", "build"]
categories = [
    "development-tools",
    "development-tools::cargo-plugins",
    "development-tools::build-utils",
    "command-line-utilities",
]

[dependencies]
anyhow = "1.0"
bs58 = "0.5.0"
camino = "1.1.1"
cargo_metadata = "0.17.0"
clap = { version = "4.3.21", features = ["derive", "env"] }
colored = "2.0"
env_logger = "0.10.0"
log = "0.4"
rustc_version = "0.4"
serde_json = "1.0"
sha2 = "0.10"
symbolic-debuginfo = "12.3.0"
schemars = "0.8"
near-abi = { version = "0.3.0", features = ["__chunked-entries"] }
libloading = "0.8.0"
zstd = "0.12.4"
atty = "0.2.14"
askama = "0.12.0"
rust-embed = "8.0.0"
structopt = "0.3.26"
interactive-clap = "0.2.4"
strum = { version = "0.24.0", features = ["derive"] }
strum_macros = "0.24"
color-eyre = "0.6"
derive_more = "0.99.9"
inquire = "0.6"
shell-words = "1.0.0"
near-cli-rs = { version = "0.5.2" }
